# Generated by Django 5.2.5 on 2025-08-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0009_alter_recepty_ingredience_makrozivinyrecepty'),
        ('user_profile', '0009_food_jednotka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jidelnicek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
                ('seznam_obedu', models.ManyToManyField(related_name='obed_recepty', to='chat.recepty')),
                ('seznam_snidani', models.ManyToManyField(related_name='snidane_recepty', to='chat.recepty')),
                ('seznam_svacin1', models.ManyToManyField(related_name='svacina1_recepty', to='chat.recepty')),
                ('seznam_svacin2', models.ManyToManyField(related_name='svacina2_recepty', to='chat.recepty')),
                ('seznam_veceri', models.ManyToManyField(related_name='vecere_recepty', to='chat.recepty')),
            ],
        ),
        migrations.CreateModel(
            name='VybraneRecepty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vybrany_obed', to='chat.recepty')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
                ('snidane', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vybrana_snidane', to='chat.recepty')),
                ('svacina1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vybrana_svacina1', to='chat.recepty')),
                ('svacina2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vybrana_svacina2', to='chat.recepty')),
                ('vecere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vybrana_vecere', to='chat.recepty')),
            ],
        ),
    ]
