# Generated by Django 5.2.5 on 2025-08-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_recepty_ingredience_makrozivinyrecepty'),
        ('muj_den', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jidelnicek',
            name='seznam_obedu',
            field=models.ManyToManyField(blank=True, null=True, related_name='obed_recepty', to='chat.recepty'),
        ),
        migrations.AlterField(
            model_name='jidelnicek',
            name='seznam_snidani',
            field=models.ManyToManyField(blank=True, null=True, related_name='snidane_recepty', to='chat.recepty'),
        ),
        migrations.AlterField(
            model_name='jidelnicek',
            name='seznam_svacin1',
            field=models.ManyToManyField(blank=True, null=True, related_name='svacina1_recepty', to='chat.recepty'),
        ),
        migrations.AlterField(
            model_name='jidelnicek',
            name='seznam_svacin2',
            field=models.ManyToManyField(blank=True, null=True, related_name='svacina2_recepty', to='chat.recepty'),
        ),
        migrations.AlterField(
            model_name='jidelnicek',
            name='seznam_veceri',
            field=models.ManyToManyField(blank=True, null=True, related_name='vecere_recepty', to='chat.recepty'),
        ),
    ]
