# Generated by Django 5.2.5 on 2025-09-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muj_den', '0003_alter_jidelnicek_seznam_obedu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vybranerecepty',
            name='obed_snezen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vybranerecepty',
            name='snidane_snezena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vybranerecepty',
            name='svacina1_snezena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vybranerecepty',
            name='svacina2_snezena',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vybranerecepty',
            name='vecere_snezena',
            field=models.BooleanField(default=False),
        ),
    ]
