# Generated by Django 5.2.5 on 2025-09-11 15:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_aktivita'),
        ('muj_den', '0004_vybranerecepty_obed_snezen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jidelnicek',
            name='seznam_obedu',
        ),
        migrations.RemoveField(
            model_name='jidelnicek',
            name='seznam_snidani',
        ),
        migrations.RemoveField(
            model_name='jidelnicek',
            name='seznam_svacin1',
        ),
        migrations.RemoveField(
            model_name='jidelnicek',
            name='seznam_svacin2',
        ),
        migrations.RemoveField(
            model_name='jidelnicek',
            name='seznam_veceri',
        ),
        migrations.CreateModel(
            name='JidelnicekRecept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_factor', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=5)),
                ('chod', models.CharField(blank=True, max_length=50, null=True)),
                ('snezeno', models.BooleanField(default=False)),
                ('recept', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.recepty')),
            ],
        ),
        migrations.AddField(
            model_name='jidelnicek',
            name='recepty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muj_den.jidelnicekrecept'),
        ),
        migrations.DeleteModel(
            name='VybraneRecepty',
        ),
    ]
