# Generated by Django 5.2.5 on 2025-09-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muj_den', '0005_remove_jidelnicek_seznam_obedu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jidelnicek',
            name='recepty',
        ),
        migrations.AddField(
            model_name='jidelnicekrecept',
            name='jidelnicek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muj_den.jidelnicek'),
        ),
    ]
