# Generated by Django 5.2.5 on 2025-09-12 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_aktivita'),
        ('muj_den', '0006_remove_jidelnicek_recepty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jidelnicekrecept',
            name='recept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.recepty'),
        ),
    ]
