# Generated by Django 5.2.5 on 2025-08-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('sender', models.CharField(max_length=128)),
                ('time_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
