# Generated by Django 5.2.5 on 2025-08-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
