# Generated by Django 5.2.5 on 2025-08-17 16:21

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_diety', models.CharField(max_length=150)),
                ('podstata', models.TextField()),
                ('vyhody', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('neni_doporuceno_pro', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Potraviny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=150)),
                ('popis', models.TextField()),
                ('vyhody', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('nejlepsi_pro', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
                ('nekonzumujte_pokud', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recepty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=150)),
                ('ingredience', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
                ('instrukce', models.TextField()),
                ('vhodne_pro', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=150), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Situace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popis_situace', models.TextField()),
                ('rada', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StylyKomunikace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('styl', models.CharField(max_length=100)),
                ('priklad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Makroziviny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilkoviny_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sacharidy_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tuky_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('potravina', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.potraviny')),
            ],
        ),
    ]
