# Generated by Django 5.2.5 on 2025-08-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_podstata_diety_popis_diety_embedding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makroziviny',
            name='kalorie',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
