# Generated by Django 5.2.5 on 2025-08-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_makroziviny_kalorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recepty',
            name='cas_pripravy_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recepty',
            name='teplota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recepty',
            name='typ_jidla',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
