# Generated by Django 5.2.5 on 2025-08-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_recepty_cas_pripravy_min_recepty_teplota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepty',
            name='ingredience',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='MakrozivinyRecepty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kalorie', models.IntegerField(blank=True, null=True)),
                ('bilkoviny_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sacharidy_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tuky_gramy', models.DecimalField(decimal_places=2, max_digits=6)),
                ('recept', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.recepty')),
            ],
        ),
    ]
