# Generated by Django 5.2.5 on 2025-09-10 16:20

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_recepty_ingredience_makrozivinyrecepty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aktivita_id', models.CharField(blank=True, max_length=64, null=True)),
                ('typ_aktivity', models.CharField(blank=True, max_length=64, null=True)),
                ('kategorie', models.CharField(blank=True, max_length=64, null=True)),
                ('met_hodnota', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('popis', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
            ],
        ),
    ]
