# Generated by Django 5.2.5 on 2025-08-20 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_makroziviny_kalorie'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='potravina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.potraviny'),
        ),
    ]
