# Generated by Django 5.2.5 on 2025-08-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_food_potravina'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='hmotnost_g',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
