# Generated by Django 5.2.5 on 2025-08-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_profile_dieta_profile_je_aktivni_profile_jmeno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='specialni_zdravotni_situace',
            new_name='zdravotni_omezeni',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='je_aktivni',
        ),
        migrations.AddField(
            model_name='profile',
            name='aktivita',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pitny_rezim_litry',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
