# Generated by Django 5.2.5 on 2025-08-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_specialni_zdravotni_situace_profile_zdravotni_omezeni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='jednoduchy_formular',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
