# Generated by Django 5.2.5 on 2025-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_profile_obvod_boku_cm_profile_obvod_krku_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='jednotka',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
