# Generated by Django 5.2.5 on 2025-09-10 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_aktivita'),
        ('user_profile', '0009_food_jednotka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cas_min', models.IntegerField(blank=True, null=True)),
                ('aktivita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.potraviny')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.profile')),
            ],
        ),
    ]
