# Generated by Django 5.2.5 on 2025-09-10 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_aktivita'),
        ('user_profile', '0010_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='aktivita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.aktivita'),
        ),
    ]
